services:
  jekyll:
    build: .
    ports:
      - "4000:4000" # Jekyll server
      - "35729:35729" # LiveReload
    volumes:
      - .:/site
      - bundle_cache:/usr/local/bundle
    environment:
      - JEKYLL_ENV=development
    command: bundle exec jekyll serve --host 0.0.0.0 --livereload --force_polling

volumes:
  bundle_cache:
